server:
  port: 8082
  
eureka:
  instance: 
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.19.0.4:8081/eureka
    register-with-eureka: true

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
    
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  config:
    type: signed